In [477]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt 
import seaborn as sns

In [478]:
# Reading dataset
unknowndataset = pd.read_csv("Assignment3-Unknown-Dataset.csv")
unknowndataset

,row ID,age,job,marital,education,default,housing,loan,contact,month,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,state
0,Row0,57,services,married,high.school,unknown,no,no,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,VIC
1,Row1,40,admin.,married,basic.6y,no,no,no,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,NT
2,Row2,41,blue-collar,married,unknown,unknown,no,no,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,TAS
3,Row3,50,blue-collar,married,basic.9y,no,yes,yes,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,NSW
4,Row4,39,management,single,basic.9y,unknown,no,no,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,ACT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6585,Row6585,41,technician,married,professional.course,no,yes,no,cellular,nov,...,2,999,0,nonexistent,-1.1,?,-50.8,1.039,4963.6,WA
6586,Row6586,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,...,2,4,1,success,-1.1,?,-50.8,1.035,4963.6,QLD
6587,Row6587,31,admin.,single,university.degree,no,yes,no,cellular,nov,...,1,999,0,nonexistent,-1.1,?,-50.8,1.031,4963.6,QLD
6588,Row6588,62,retired,married,university.degree,no,yes,no,cellular,nov,...,1,1,6,success,-1.1,?,-50.8,1.031,4963.6,TAS
6589,Row6589,62,retired,married,university.degree,no,no,no,cellular,nov,...,2,6,3,success,-1.1,?,-50.8,1.031,4963.6,VIC

In [479]:
# Total number of columns
print(len(unknowndataset.columns))

22

# Data preprocessing

In [480]:
#Check missing values in each columns 
missing_values = unknowndataset.isin(['?', 'unknown']).sum()
print(missing_values)

row ID               0
age                  0
job                 53
marital             13
education          289
default           1344
housing            151
loan               151
contact              0
month                0
day_of_week          0
duration             0
campaign             0
pdays              223
previous             0
poutcome             0
emp.var.rate       141
cons.price.idx      22
cons.conf.idx        0
euribor3m            0
nr.employed        403
state                0
dtype: int64

## Clean data
- Keep all columns

In [481]:
# Impute other attributes
for column in unknowndataset:
    # Replace missing values with pandas NaN null then fill
    unknowndataset[column] = unknowndataset[column].replace(['?', 'unknown'], pd.NA)
    # Check if there are missing values null
    if unknowndataset[column].isnull().sum() > 0:
        if unknowndataset[column].dtype == 'object':
            fill_mode = unknowndataset[column].mode()[0] # incase many modes, get the first one
            unknowndataset[column].fillna(fill_mode, inplace=True)
        else:
            # Numeric column → impute with mean
            fill_mean = unknowndataset[column].mean()
            unknowndataset[column].fillna(fill_mean, inplace=True)

/var/folders/vj/3d155nx56n3g1y64vxb08pcw0000gn/T/ipykernel_18612/2272096803.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unknowndataset[column].fillna(fill_mode, inplace=True)

In [482]:
unknowndataset

,row ID,age,job,marital,education,default,housing,loan,contact,month,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,state
0,Row0,57,services,married,high.school,no,no,no,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,VIC
1,Row1,40,admin.,married,basic.6y,no,no,no,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,NT
2,Row2,41,blue-collar,married,university.degree,no,no,no,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,TAS
3,Row3,50,blue-collar,married,basic.9y,no,yes,yes,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,NSW
4,Row4,39,management,single,basic.9y,no,no,no,telephone,may,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,ACT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6585,Row6585,41,technician,married,professional.course,no,yes,no,cellular,nov,...,2,999,0,nonexistent,-1.1,93.994,-50.8,1.039,4963.6,WA
6586,Row6586,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,...,2,4,1,success,-1.1,93.994,-50.8,1.035,4963.6,QLD
6587,Row6587,31,admin.,single,university.degree,no,yes,no,cellular,nov,...,1,999,0,nonexistent,-1.1,93.994,-50.8,1.031,4963.6,QLD
6588,Row6588,62,retired,married,university.degree,no,yes,no,cellular,nov,...,1,1,6,success,-1.1,93.994,-50.8,1.031,4963.6,TAS
6589,Row6589,62,retired,married,university.degree,no,no,no,cellular,nov,...,2,6,3,success,-1.1,93.994,-50.8,1.031,4963.6,VIC

In [483]:
# Check again if there are any missing values
any_missing_values = unknowndataset.isin(['?', 'unknown']).sum()
any_missing_values

row ID            0
age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
state             0
dtype: int64

In [484]:
# Check unique values
for col in unknowndataset.columns:
    print(f"Column: {col}")
    print(unknowndataset[col].unique())

Column: row ID
['Row0' 'Row1' 'Row2' ... 'Row6587' 'Row6588' 'Row6589']
Column: age
[57 40 41 50 39 30 59 55 42 47 48 33 35 37 44 54 52 51 43 24 38 36 46 34
 27 60 45 49 31 26 58 32 53 56 29 28 25 23 22 21 20 18 61 88 70 77 68 63
 66 72 82 64 67 69 19 75 85 62 71 65 76 73 74 80 83 78 79 84]
Column: job
['services' 'admin.' 'blue-collar' 'management' 'unemployed' 'technician'
 'self-employed' 'entrepreneur' 'student' 'retired' 'housemaid']
Column: marital
['married' 'single' 'divorced']
Column: education
['high.school' 'basic.6y' 'university.degree' 'basic.9y' 'basic.4y'
 'professional.course' 'illiterate']
Column: default
['no']
Column: housing
['no' 'yes']
Column: loan
['no' 'yes']
Column: contact
['telephone' 'cellular']
Column: month
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'mar' 'apr' 'sep']
Column: day_of_week
['mon' 'tue' 'wed' 'thu' 'fri']
Column: duration
[ 149  151   55  353  195   38  181   93  233  362  336  577   22  161
  449  164  357  337  272  529  180  197  257  229  190  293  262  345
  193  243  186  165  559  506  427  240  673  138  228  277  172   67
  248  366   64  189  119   58   92    5  742  200  267  106  364  230
  196  316  213  220  113  379  168  210  184  290  253  124  227  245
  208  225  276  241  246  134   27  358  448  264  278   46   80  198
  221  247  502  310  390  140  424  135  389   78  201  191  312  100
  226  333  322  160  477   13  296  132  144  112  421  207  303   88
  329  275  285   96  395  446  231  992  425  439  615  359  236  123
  287  255  591  463  256  143   69   97  511  294  614  166  371   72
  209  126  153  418  175  283  212  139   73  244  155  489   81  865
  238   31  308  125  328  183   41  202  159  194 1119  158  187  784
  108  131   74  156  102  280  141  136  347  234  173  205   12  224
  133  163  128  169  672  192  330   84   89  185  103  117  203   85
   94  617  215  375   45   70  705  341   44  576   25  258  211   71
   87   91  142  150  365 1692  129   20  251  174  412  127   79 1713
  338  332   49   26  177  115  878   18   43   77 1534  291  147  289
  460  346  396  286  566  120  409   33  486   63  388  146  315  171
  413  335   98  484  467   24  274  518  101  520  178  295  370  148
   39  121  334  122  683   82   36  521   59  342  394  109   34  788
  431  437  214  116  492  152  360  438  313  219  162  381  260   48
  606  105  488  456  452  858  461  249  263  216  829  387  265   75
    8  217  302  232  668  423  154  594 1423  104  747  311   90 1013
   76  349  646  517  735  552  305  206  435  599  464  218   99   50
   57  719   51  318  118  465  973   21  399  964  384   52  404  548
   17  487  697    7  284  222  377  601  130  731   37  688  803  306
  326 1230   95  299  344  386 2680  242  269   14   40  698  292  680
  408  730  385  261  237  393 1187  374   83  343  610  167  314  107
   53  110  182  532  297   68  369  320  618  447  309  774  378  199
  834  592  137 1042  415  650  625  304    6  300   10  340  725  204
  692  565  420  490  958  530  759  445   32  544  795  738  563  176
  899  890 1162  860  111  832   86  713  250  339  621 1073  700  354
  223  911  252  270  665  567  541  472  361   29 1392  430  426   60
  368   62  974  351  473  145  327  239  470  695  741  414  157  469
  674  550   19  513  355  301  574  570  348 1043 1168  372  938  114
  519  373  543  268  392 1210  317  675  170  279   47  376  545  643
  411  600   23  733  619  791   66  514  936  932  417  792 1611 1185
  352  900  859  382 1109  828  660  254  868  633  363 1097  273  891
 1044  367  266  466  658  498   56  282  685  235   61   16  402  605
  179  479  288  676  641 1340  406  495 1259  350  497  397  324  433
 1449   42   65  271  701  581 1084  400  586  817  805  718  451  939
  453   28  442  800  434 2653 1330  298  383  422  443  940  440  436
 1137  478   54  480  583  678  904  188  454  580 1238  523   30 1345
  681  979  637  744  356  307  802 1066  593  677  512 1012  471  534
 1663 1478 1422    9  585  819   11  662  481  528 3183  856 1576  407
  491  722 1103 1356  459 1467  457  281  756  259  634  325 1767  632
  861 1111  679  590  628 1139  391  496  854  880  323  428  604  724
  564  455  970 1389  636 1081  853  767  549  766 1062 1669 1071  546
  416  808  716  955  462  578  771  715  401  781 1150 1432 1018  319
  524  613  321  804  504 1390  536  558  978  640  671  835 1127  728
  589 1039  474 1342  522  930  929  712  843  630 1833  654 1408  493
  503  870  933  505  380   15  823  988  901  631  458  441 1492  720
  796  483  657  507  946  661  551  624 1065 1076  710  647  790  597
 1140  468  984 1171  509  595  962  921   35 1110  837  553  704 1357
  902  763  666  642 1336  419  994  629 1000 1206  588  667  607  734
  663  971 1181  696  864 1476  827  740  753  762  956  331  950  687
  587 1032  561  582  649  500  875  975  703  656  508  572 1241  547
  714 1374  664    0  516  787  961  398 2016  669  527  499  540  501
  555  635 1855  727  515 1132  682 1554  648  925  862  638 1283  622
 1049  690  623 1337 1307  575 1192 1058  485  554  768 1145  871  884
 1059 2453  670  906  888  905  475 1435 2316  562  612  764  850  945
  405 1038  743 1122  693 1285  432  557  981  531  840 1161 1130  818
  476 1348  444 1958  535  841 1240  895 1090  659  568  954  644 1079
  611  903  811  482  560 1806  908 1077  813 1243 1448 1642  429  798
  772  877 1272  639  816  844  609  897  526  699  777 1279  786 1075
  691 1380  739 1598 2301 1434 1359 1346 1094  883 1057  826  537 1019
 1117  711  849 1386 1106 1226 1020 1002 1118 1092 1233 1248  709  824
  893  689  450 1143  403  820  538  775 1720  737  410  957  951  815
  651  510 1363  729 1298  608 1246    4 1556]
Column: campaign
[ 1  2  3  6  5  4  7 10 12 19  9 11 14 25 15  8 17 13 26 21 18 23 20 16
 28 24 31 41 22 30 43 33 27]
Column: pdays
['999' '4' '5' '6' '3' '1' '11' '8' '9' '2' '0' '10' '12' '7' '13' '15'
 '16' '14' '17' '22' '27' '20']
Column: previous
[0 1 2 3 4 5 6]
Column: poutcome
['nonexistent' 'failure' 'success']
Column: emp.var.rate
['1.1' '1.4' '-0.1' '-0.2' '-1.8' '-2.9' '-3.4' '-3' '-1.7' '-1.1']
Column: cons.price.idx
['93.994' '94.465' '93.918' '93.444' '93.798' '93.2' '92.756' '92.843'
 '93.075' '92.893' '92.963' '92.469' '92.201' '92.379' '92.431' '92.649'
 '92.713' '93.369' '93.749' '93.876' '94.055' '94.215' '94.027' '94.199'
 '94.601' '94.767']
Column: cons.conf.idx
[-36.4 -41.8 -42.7 -36.1 -40.4 -42.  -45.9 -50.  -47.1 -46.2 -40.8 -33.6
 -31.4 -29.8 -26.9 -30.1 -33.  -34.8 -34.6 -40.  -39.8 -40.3 -38.3 -37.5
 -49.5 -50.8]
Column: euribor3m
[4.857 4.856 4.855 4.859 4.86  4.858 4.864 4.865 4.866 4.967 4.961 4.959
 4.958 4.96  4.962 4.955 4.947 4.956 4.966 4.963 4.957 4.968 4.97  4.965
 4.964 5.045 5.    4.936 4.921 4.794 4.76  4.7   4.663 4.474 4.286 4.245
 4.223 4.191 4.153 4.12  4.076 4.021 3.901 3.669 3.563 1.811 1.799 1.778
 1.757 1.726 1.703 1.687 1.663 1.64  1.629 1.614 1.602 1.56  1.548 1.538
 1.531 1.52  1.498 1.483 1.479 1.466 1.453 1.445 1.435 1.423 1.415 1.41
 1.405 1.406 1.4   1.392 1.384 1.372 1.365 1.354 1.344 1.334 1.327 1.313
 1.299 1.291 1.281 1.266 1.25  1.244 1.259 1.264 1.27  1.262 1.26  1.268
 1.286 1.252 1.215 1.206 1.099 1.085 1.072 1.059 1.044 1.029 0.944 0.937
 0.914 0.908 0.884 0.883 0.881 0.879 0.873 0.869 0.861 0.859 0.854 0.851
 0.849 0.843 0.838 0.834 0.829 0.825 0.821 0.819 0.813 0.809 0.803 0.797
 0.788 0.781 0.773 0.77  0.768 0.743 0.741 0.753 0.754 0.752 0.744 0.74
 0.742 0.739 0.737 0.735 0.733 0.73  0.731 0.728 0.724 0.722 0.72  0.719
 0.715 0.714 0.716 0.718 0.712 0.71  0.709 0.708 0.706 0.707 0.7   0.655
 0.654 0.653 0.652 0.651 0.65  0.649 0.646 0.643 0.639 0.637 0.635 0.636
 0.64  0.642 0.644 0.645 0.659 0.663 0.668 0.672 0.677 0.682 0.683 0.684
 0.688 0.692 0.695 0.697 0.699 0.701 0.702 0.704 0.713 0.723 0.727 0.729
 0.732 0.748 0.761 0.782 0.79  0.793 0.802 0.81  0.822 0.827 0.835 0.84
 0.846 0.87  0.876 0.885 0.889 0.893 0.896 0.899 0.898 0.9   0.904 0.905
 0.903 0.89  0.891 0.888 0.886 0.882 0.88  0.878 0.877 0.942 0.953 0.959
 0.965 0.972 0.977 0.982 0.985 0.987 1.    1.016 1.025 1.032 1.043 1.05
 1.049 1.048 1.046 1.041 1.04  1.039 1.035 1.031]
Column: nr.employed
['5191' '5228.1' '5195.8' '5176.3' '5099.1' '5076.2' '5017.5' '5023.5'
 '5008.7' '4991.6' '4963.6']
Column: state
['VIC' 'NT' 'TAS' 'NSW' 'ACT' 'SA' 'QLD' 'WA']

# Normalization
- Using minmax scaling
- For duration, pdays,emp.var.rate	cons.price.idx	cons.conf.idx, euribor3m

In [485]:
from sklearn.preprocessing import MinMaxScaler

# Scaler
min_max_scaler = MinMaxScaler()

# Chosen columns to normalise
col_to_normalise = [    'age', 'duration','emp.var.rate','cons.price.idx', 'cons.conf.idx', 
    'euribor3m', 'nr.employed', 'pdays']

# Normalize the columns
for col in col_to_normalise:
    unknowndataset[col] = min_max_scaler.fit_transform(unknowndataset[col].values.reshape(-1, 1))

# Data transformation
- Encode job, marital, education, contact, month, day_of_week, campaign, poutcome, state, subscribed? 
- Encode binary columns: deafult, housing, loan, previous

In [486]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Initialize the LabelEncoder
label_encoder = LabelEncoder()
label_encode_columns = ['job', 'marital', 'education', 'campaign', 'month', 'day_of_week', 'state']

# Apply LabelEncoder to each column
for column in label_encode_columns:
    unknowndataset[column] = label_encoder.fit_transform(unknowndataset[column].values.reshape(-1, 1))

# Initialize the OneHoteEncoder
onehot_encoder = OneHotEncoder(dtype=int, sparse_output=False)
onehot_encode_columns = ['contact', 'default', 'housing', 'loan', 'poutcome', 'previous']
for col in onehot_encode_columns:
        unknowndataset[col] = onehot_encoder.fit_transform(unknowndataset[col].values.reshape(-1, 1))

/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

# Feature selection
- Similar to marketing dataset
- Filter relevant columns

In [487]:
sub_unknowndataset = unknowndataset[['row ID', 'duration', 'campaign', 'nr.employed', 'euribor3m', 'emp.var.rate', 'cons.price.idx','previous', 'marital', 'education']]

In [488]:
sub_unknowndataset

,row ID,duration,campaign,nr.employed,euribor3m,emp.var.rate,cons.price.idx,previous,marital,education
0,Row0,0.046811,0,0.859735,0.957370,0.937500,0.698753,1,1,3
1,Row1,0.047440,0,0.859735,0.957370,0.937500,0.698753,1,1,1
2,Row2,0.017279,0,0.859735,0.957370,0.937500,0.698753,1,1,6
3,Row3,0.110902,0,0.859735,0.957370,0.937500,0.698753,1,1,2
4,Row4,0.061263,0,0.859735,0.957370,0.937500,0.698753,1,2,2
...,...,...,...,...,...,...,...,...,...,...
6585,Row6585,0.058121,1,0.000000,0.091610,0.479167,0.698753,1,1,5
6586,Row6586,0.109017,1,0.000000,0.090703,0.479167,0.698753,0,1,0
6587,Row6587,0.110902,0,0.000000,0.089796,0.479167,0.698753,1,2,6
6588,Row6588,0.065347,0,0.000000,0.089796,0.479167,0.698753,0,1,6
6589,Row6589,0.151744,1,0.000000,0.089796,0.479167,0.698753,0,1,6

In [489]:
X_unknown = sub_unknowndataset.drop(columns=['row ID'])

# Prediction

In [490]:
import joblib

# Load the trained models
dt_model = joblib.load('dt_model.pkl')
rf_model = joblib.load('rf_model.pkl')
knn_model = joblib.load('knn_model.pkl')
ada_model = joblib.load('ada_model.pkl')
nn_model = joblib.load('nn_model.pkl')
nusvc_model = joblib.load('nusvc_model.pkl')

In [491]:
# Prediction
y_pred_dt = dt_model.predict(X_unknown)
y_pred_rf = rf_model.predict(X_unknown)
y_pred_knn = knn_model.predict(X_unknown)
y_pred_ada = ada_model.predict(X_unknown)
y_pred_nn = nn_model.predict(X_unknown)
y_pred_nusvc = nusvc_model.predict(X_unknown)

In [493]:
# Output csv
# For decision tree
dt_output = sub_unknowndataset[['row ID']]
dt_output['subscribed'] = y_pred_dt
dt_output.to_csv('dt_predictions.csv', index=False)

# For random forest
rf_output = sub_unknowndataset[['row ID']]
rf_output['subscribed'] = y_pred_rf
rf_output.to_csv('rf_predictions.csv', index=False)

# For knn
knn_output = sub_unknowndataset[['row ID']]
knn_output['subscribed'] = y_pred_knn
knn_output.to_csv('knn_predictions.csv', index=False)

# For ada
ada_output = sub_unknowndataset[['row ID']]
ada_output['subscribed'] = y_pred_ada
ada_output.to_csv('ada_predictions.csv', index=False)

# For nn
nn_output = sub_unknowndataset[['row ID']]
nn_output['subscribed'] = y_pred_nn
nn_output.to_csv('nn_predictions.csv', index=False)

# For svm
nusvc_output = sub_unknowndataset[['row ID']]
nusvc_output['subscribed'] = y_pred_nusvc
nusvc_output.to_csv('nusvc_predictions.csv', index=False)

#Verfiy
print("All saved")

All saved

/var/folders/vj/3d155nx56n3g1y64vxb08pcw0000gn/T/ipykernel_18612/4085311529.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dt_output['subscribed'] = y_pred_dt
/var/folders/vj/3d155nx56n3g1y64vxb08pcw0000gn/T/ipykernel_18612/4085311529.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rf_output['subscribed'] = y_pred_rf
/var/folders/vj/3d155nx56n3g1y64vxb08pcw0000gn/T/ipykernel_18612/4085311529.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  knn_output['subscribed'] = y_pred_knn
/var/folders/vj/3d155nx56n3g1y64vxb08pcw0000gn/T/ipykernel_18612/4085311529.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ada_output['subscribed'] = y_pred_ada
/var/folders/vj/3d155nx56n3g1y64vxb08pcw0000gn/T/ipykernel_18612/4085311529.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nn_output['subscribed'] = y_pred_nn
/var/folders/vj/3d155nx56n3g1y64vxb08pcw0000gn/T/ipykernel_18612/4085311529.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nusvc_output['subscribed'] = y_pred_nusvc

In [494]:
print(sub_unknowndataset.shape[0])  #check match kaggle

6590